// weapons

import { PLAYER_SKILL } from './playerSkills';
import { PLAYER_STAT } from './stats';

export const WEAPON_TYPE = {
	SWORD: 'SWORD',
	LANCE: 'LANCE',
	AXE: 'AXE',
	BOW: 'BOW',
	FISTS: 'FISTS',
	HEAVY_ARMOR: 'HEAVY_ARMOR',
	RIDING: 'RIDING',
	REASON: 'REASON',
	FAITH: 'FAITH',
	LEADERSHIP: 'LEADERSHIP'
};

export const WEAPON_TYPE_TO_LABEL = {
	[WEAPON_TYPE.SWORD]: 'Sword',
	[WEAPON_TYPE.LANCE]: 'Lance',
	[WEAPON_TYPE.AXE]: 'Axe',
	[WEAPON_TYPE.BOW]: 'Bow',
	[WEAPON_TYPE.FISTS]: 'Fists',
	[WEAPON_TYPE.HEAVY_ARMOR]: 'Heavy Armor',
	[WEAPON_TYPE.RIDING]: 'Riding',
	[WEAPON_TYPE.REASON]: 'Reason',
	[WEAPON_TYPE.FAITH]: 'Faith',
	[WEAPON_TYPE.LEADERSHIP]: 'Leadership'
};

export const WEAPON_TYPE_TO_STAT = {
	[WEAPON_TYPE.SWORD]: [PLAYER_STAT.STR],
	[WEAPON_TYPE.LANCE]: [PLAYER_STAT.STR, PLAYER_STAT.DEX],
	[WEAPON_TYPE.AXE]: [PLAYER_STAT.STR],
	[WEAPON_TYPE.BOW]: [PLAYER_STAT.DEX],
	[WEAPON_TYPE.FISTS]: [PLAYER_STAT.STR, PLAYER_STAT.DEX],
	[WEAPON_TYPE.HEAVY_ARMOR]: [PLAYER_STAT.CON],
	[WEAPON_TYPE.RIDING]: [PLAYER_SKILL.ANIMAL_HANDLING],
	[WEAPON_TYPE.REASON]: [PLAYER_STAT.INT],
	[WEAPON_TYPE.FAITH]: [PLAYER_STAT.INT],
	[WEAPON_TYPE.LEADERSHIP]: [PLAYER_STAT.WIS, PLAYER_STAT.CHA]
};
